testing restart service pipeline function

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -26,6 +26,20 @@ variables:
 
   DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501
 
+  # Values for non-build jobs
+  RESTART_SERVICE:
+    value: "false"
+    options:
+      - "false"
+      - "true"
+  RESTART_SERVICE_ENV:
+    options:
+      - "dev"
+      - "stage-a"
+      - "stage-b"
+      - "prod-a1"
+      - "prod-a2"
+
 stages:
   - app_build
   - scan
@@ -37,6 +51,7 @@ stages:
   - production-2
   - performance
   - cleanup
+  - jobs
 
 workflow:
   rules:
@@ -113,6 +128,42 @@ build_image:
     - if: $CI_COMMIT_TAG
       when: never
     - when: on_success
+
+restart_service:
+  stage: jobs
+  allow_failure: false
+  image:
+    name: bitnami/kubectl
+  script:
+    - |
+      if [$RESTART_SERVICE_ENV == "dev" ]; then
+        export RUMBLE_NAMESPACE=guild-service-dev
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:platform-services
+      elif [$RESTART_SERVICE_ENV == "stage-a"]; then
+        export RUMBLE_NAMESPACE=guild-service-stage-a
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:platform-services
+      elif [$RESTART_SERVICE_ENV == "stage-b"]; then
+        export RUMBLE_NAMESPACE=guild-service-stage-b
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:platform-services
+      elif [$RESTART_SERVICE_ENV == "prod-a1"]; then
+        export RUMBLE_NAMESPACE=guild-service
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:prod-a1-platform-services
+      elif [$RESTART_SERVICE_ENV == "prod-a2"]; then
+        export RUMBLE_NAMESPACE=guild-service
+        export RUMBLE_CONTEXT=platform-services/platform-services-agent:prod-a2-platform-services
+      else
+        echo "Somehow an invalid environment was selected"
+        exit 666
+      fi
+      echo "Using $RUMBLE_CONTEXT to delete all pods from $RUMBLE_NAMESPACE"
+    - |
+      if [ ! -z "$RUMBLE_NAMESPACE" ]; then
+        kubectl get pods -o yaml -n $NAMESPACE | kubectl delete -f -
+      fi
+  rules:
+    - if: 'RESTART_SERVICE == true'
+      when: always
+
 
 include:
   - '/.gitlab/deploy-k8s.yaml'
